"""add is_public column to profile table

Revision ID: 348c521f549d
Revises: 9e9d0abeae8b
Create Date: 2026-05-30 17:31:03.562999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348c521f549d'
down_revision = '9e9d0abeae8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        # Added server_default=sa.text('1') so SQLite can safely populate existing rows with True (1)
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
